# numpy exercises


#### 1. Import the numpy package under the name `np`

In [1]:
import numpy as np

#### 2. Create a null vector of size 10.

In [7]:
zeros_arr = np.zeros(10)
print(zeros_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Print the memory size of an array.

In [9]:
print(np.size(zeros_arr))

10


#### 4. Create a null vector of size 10 but the fifth value should be 1.

In [12]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 5. Create a vector with values ranging from 10 to 49.

In [14]:
v = np.arange(10, 50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 6. Reverse a vector (first element becomes last).

In [17]:
y = np.random.randint(0,10,10)
print(y)
reversed_arr = y[::-1]
print(reversed_arr)

[6 5 6 2 6 7 4 8 6 7]
[7 6 8 4 7 6 2 6 5 6]


#### 7. Create a 3x3 matrix with values ranging from 0 to 8.

In [21]:
m = np.arange(0,9)
print(m)
print(m.reshape((3,3)))

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

In [27]:
x = np.array([[1,2,0,0,4,0]])
print(np.nonzero(x)[1])

[0 1 4]


#### 9. Create a 3x3 identity matrix.

In [28]:
y = np.identity(3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 10. Create a 3x3x3 array with random values.

In [31]:
m = np.random.random((3,3,3))
print(m)

[[[0.94609098 0.77150411 0.30464   ]
  [0.40181672 0.36110752 0.9548391 ]
  [0.35617924 0.99769461 0.39960658]]

 [[0.73968924 0.13973049 0.15883804]
  [0.92716465 0.61964256 0.79686824]
  [0.41291427 0.73137455 0.9739003 ]]

 [[0.10623983 0.8901091  0.65582496]
  [0.97580855 0.50056079 0.15895495]
  [0.93875993 0.77811336 0.27142864]]]


#### 11. Create a 10x10 array with random values and find the minimum and maximum values.

In [33]:
n = np.random.random((10, 10))
print(n)
print(f"Max value: {np.max(n)}")
print(f"Min value: {np.min(n)}")

[[6.62339148e-01 6.85875124e-01 1.52247029e-01 7.33658754e-01
  1.37601303e-04 8.55822393e-01 6.39503622e-01 2.86657823e-01
  5.69859734e-01 9.55086552e-01]
 [2.13588155e-01 1.66488956e-01 4.64024016e-01 4.52101485e-01
  9.64676970e-01 8.84421885e-01 6.05005494e-01 4.16442626e-01
  9.74956884e-01 7.94104682e-01]
 [2.28873750e-03 5.38814805e-01 8.25635761e-01 7.90975331e-02
  2.64795942e-01 9.05975098e-01 7.25380463e-01 9.41078601e-01
  9.68816653e-01 6.96543914e-01]
 [5.95027793e-01 9.02265447e-01 3.11125173e-02 2.31446599e-01
  8.24142024e-01 9.40131066e-01 3.42654917e-01 7.67830484e-02
  8.92460831e-02 4.52266851e-01]
 [6.64186142e-01 3.66522226e-02 9.22262106e-01 5.00974539e-01
  8.29168004e-01 8.93703430e-01 1.59468371e-01 1.59853099e-01
  4.90595087e-01 2.87229741e-01]
 [5.70080495e-01 3.04260550e-01 4.03624083e-01 5.42307354e-01
  4.73370625e-02 6.16245232e-01 3.14140478e-01 7.28519305e-01
  4.20818213e-01 7.63676142e-01]
 [7.94699116e-01 8.78711932e-01 3.53395672e-01 6.67941411e

#### 12. Create a random vector of size 30 and find the mean value.

In [34]:
a = np.random.random(30)
print(a)
print(f"Mean = {np.mean(a)}")

[0.92251874 0.74209599 0.25529515 0.33562903 0.12602179 0.43356775
 0.60571148 0.60852462 0.35164814 0.00578051 0.14042837 0.87622914
 0.05689589 0.2531433  0.75074321 0.18250773 0.30778163 0.13004032
 0.9148776  0.10914058 0.07208017 0.45802778 0.65994427 0.10914606
 0.08818241 0.8286878  0.02151024 0.50401683 0.11457072 0.40629862]
Mean = 0.3790348623205454


#### 13. Create a 2d array with 1 on the border and 0 inside.

In [38]:
square = np.ones((5,5))
print(square)

square[0, :] = 1  # Top row
square[-1, :] = 1 # Bottom row
square[:, 0] = 1  # Left column
square[:, -1] = 1 # Right column
print(square)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 14. Add a border (filled with 0's) around an existing array.

In [43]:
zero_square = np.ones((5,5))
print(zero_square)
rows, cols = zero_square.shape
print(f"rows={rows}\ncols={cols}")

# Create a bigger array filled with 0s
padded = np.zeros((rows + 2, cols + 2))

# Place the original array in the middle
padded[1:-1, 1:-1] = zero_square
print(padded)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
rows=5
cols=5
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 15. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [44]:
matrix = np.zeros((5, 5))
diagonal_values = np.arange(1, 5)
result_matrix = np.diag(diagonal_values, k=-1)
print(result_matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 16. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [45]:
shape = (6, 7, 8)
f_index = 99
index = np.unravel_index(f_index, shape)
print(index)

(1, 5, 3)


#### 17. Create a checkerboard 8x8 matrix using the tile function.

In [47]:
board = np.array([[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0]])
np.tile(board,(4,1))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 18. Normalize a 5x5 random matrix.

In [50]:
m = np.random.random((5,5))
norm_mat = (m - m.min()) / (m.max() - m.min())
print(norm_mat)

[[0.51560535 0.39300035 0.91116968 0.57506519 0.41936873]
 [0.90703311 0.17618159 0.83487882 0.68753724 0.6897733 ]
 [0.40701881 0.44554783 0.58546365 0.8005653  0.3102087 ]
 [0.98800558 0.32151912 0.         0.79596995 1.        ]
 [0.88249306 0.83236792 0.10069954 0.53778464 0.45986513]]


#### 19. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [51]:
matrix_A = np.random.rand(5, 3)
print("Matrix A (5x3):\n", matrix_A)

matrix_B = np.random.rand(3, 2)
print("\nMatrix B (3x2):\n", matrix_B)

product_matrix_dot = np.dot(matrix_A, matrix_B)
print("\nProduct matrix (using np.dot()):\n", product_matrix_dot)

product_matrix_at = matrix_A @ matrix_B
print("\nProduct matrix (using @ operator):\n", product_matrix_at)

Matrix A (5x3):
 [[0.09881351 0.45403418 0.36098465]
 [0.44505084 0.69924393 0.83210345]
 [0.72796505 0.41024779 0.64637347]
 [0.91635775 0.86545406 0.83193657]
 [0.11084952 0.88148994 0.37329982]]

Matrix B (3x2):
 [[0.16107119 0.83184878]
 [0.43251849 0.35657056]
 [0.09821437 0.09875193]]

Product matrix (using np.dot()):
 [[0.24774807 0.27974105]
 [0.45584532 0.70171662]
 [0.35817712 0.81566975]
 [0.60363185 1.15302186]
 [0.43577877 0.44338748]]

Product matrix (using @ operator):
 [[0.24774807 0.27974105]
 [0.45584532 0.70171662]
 [0.35817712 0.81566975]
 [0.60363185 1.15302186]
 [0.43577877 0.44338748]]


#### 20. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [78]:
arr = np.random.randint(0, 10, 20)
print(arr)
mask = mask = (arr >= 3) & (arr <= 8)

arr[mask] = -arr[mask]
print(arr)

[6 8 1 1 0 6 4 9 9 8 8 0 4 2 4 9 7 5 4 0]
[-6 -8  1  1  0 -6 -4  9  9 -8 -8  0 -4  2 -4  9 -7 -5 -4  0]


#### 21. Round away from zero a float array (both positive and negative numbers).

In [79]:
arr = np.array([1.2, -1.2, 2.7, -2.7, 0.0, 3.5, -3.5])
print(arr)
rounded = np.sign(arr) * np.ceil(np.abs(arr))

print("Rounded :", rounded)

[ 1.2 -1.2  2.7 -2.7  0.   3.5 -3.5]
Rounded : [ 2. -2.  3. -3.  0.  4. -4.]


#### 22. Find common values between two arrays.

In [81]:
array1 = np.array([0, 1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8, 9])

common_values = np.intersect1d(array1, array2)
print(common_values)

[4 5]


#### 23. Print the dates of yesterday, today and tomorrow.

In [82]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("Today: ", today)
print("Yestraday: ", yesterday)
print("Tomorrow: ", tomorrow)

Today:  2025-09-26
Yestraday:  2025-09-25
Tomorrow:  2025-09-27


#### 24. Extract the integer part of a random array of positive numbers using 4 different methods.

In [86]:
arr = np.random.uniform(0, 10, size=(3, 3))  # Random array of positive floats
integer_part_floor = np.floor(arr)
print("Original array:\n", arr)
print("Integer part using np.floor():\n", integer_part_floor)

integer_part_astype = arr.astype(int)
print("Original array:\n", arr)
print("Integer part using astype(int):\n", integer_part_astype)

integer_part_trunc = np.trunc(arr)
print("Original array:\n", arr)
print("Integer part using np.trunc():\n", integer_part_trunc)

_, integer_part_modf = np.modf(arr)
print("Original array:\n", arr)
print("Integer part using np.modf():\n", integer_part_modf)

Original array:
 [[3.42382362 4.32392461 2.97160248]
 [4.61082613 3.41636437 5.39422684]
 [5.91814348 3.4969637  1.17997359]]
Integer part using np.floor():
 [[3. 4. 2.]
 [4. 3. 5.]
 [5. 3. 1.]]
Original array:
 [[3.42382362 4.32392461 2.97160248]
 [4.61082613 3.41636437 5.39422684]
 [5.91814348 3.4969637  1.17997359]]
Integer part using astype(int):
 [[3 4 2]
 [4 3 5]
 [5 3 1]]
Original array:
 [[3.42382362 4.32392461 2.97160248]
 [4.61082613 3.41636437 5.39422684]
 [5.91814348 3.4969637  1.17997359]]
Integer part using np.trunc():
 [[3. 4. 2.]
 [4. 3. 5.]
 [5. 3. 1.]]
Original array:
 [[3.42382362 4.32392461 2.97160248]
 [4.61082613 3.41636437 5.39422684]
 [5.91814348 3.4969637  1.17997359]]
Integer part using np.modf():
 [[3. 4. 2.]
 [4. 3. 5.]
 [5. 3. 1.]]


#### 25. Create a 5x5 matrix with row values ranging from 0 to 4.

In [87]:
x = np.zeros((5, 5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 26. Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [92]:
arr = np.linspace(0, 1, num=11, endpoint=False)[1:]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 27. Create a random vector of size 10 and sort it.

In [95]:
arr = np.random.randint(0, 10, 10)
arr.sort()
print(arr)

[0 0 1 2 4 5 5 7 8 9]


#### 28. Check if two random arrays A and B are equal.

In [98]:
A = np.random.randint(0, 10, size=10)
B = np.random.randint(0, 10, size=10)

print(f"A={A}")
print(f"B={B}")

print(f"{A} == {B}: {np.array_equal(A, B)}")

A=[7 0 9 7 4 9 2 9 0 0]
B=[3 3 6 1 5 7 5 6 6 5]
[7 0 9 7 4 9 2 9 0 0] == [3 3 6 1 5 7 5 6 6 5]: False


#### 29. Make an array immutable (read-only).

In [100]:
a = np.zeros(11)
print(a)

a[1] = 2
print(a)

a.setflags(write=False)
# print("After making array immutable on attempting  second change ")
# a[1] = 7

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 30. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [101]:
cartesian_coords = np.random.rand(10, 2) * 20 - 10

x_coords = cartesian_coords[:, 0]
y_coords = cartesian_coords[:, 1]

# r = sqrt(x**2 + y**2)
radii = np.sqrt(x_coords**2 + y_coords**2)

# theta = arctan2(y, x)
angles = np.arctan2(y_coords, x_coords)

polar_coords = np.column_stack((radii, angles))

# Print the original and converted matrices to see the results
print("Original 10x2 Cartesian Coordinates Matrix:")
print(cartesian_coords)

print("\nConverted 10x2 Polar Coordinates Matrix (Radius, Angle in radians):")
print(polar_coords)

Original 10x2 Cartesian Coordinates Matrix:
[[-4.08601353  9.00944242]
 [-1.87873671 -5.96381178]
 [ 1.04362183 -3.98302745]
 [ 4.02603485  4.98424661]
 [-4.78537568  8.10353089]
 [-6.02290222  6.47755404]
 [-1.84846964  6.18945265]
 [ 0.05166896 -5.78597468]
 [-3.79985924 -7.32495539]
 [ 6.34937353 -9.86817262]]

Converted 10x2 Polar Coordinates Matrix (Radius, Angle in radians):
[[ 9.89270233  1.99657834]
 [ 6.25273561 -1.8759779 ]
 [ 4.11748153 -1.3145397 ]
 [ 6.40715779  0.89134644]
 [ 9.41100596  2.10422327]
 [ 8.84500183  2.3198397 ]
 [ 6.45957925  1.86101259]
 [ 5.78620538 -1.56186653]
 [ 8.25190291 -2.04933533]
 [11.73436726 -0.99906112]]
