In [1]:
import numpy as np

In [2]:
arr_1 = np.array([3,5,6,2,2])
print(arr_1)
arr_2 = np.array([[5,4,3,2],[2,5,6,7]])
print('\n', arr_2)
arr_3 = np.array([[5,4,3,2],[2,5,6,7],[6,7,8,4]])
print('\n', arr_3)

[3 5 6 2 2]

 [[5 4 3 2]
 [2 5 6 7]]

 [[5 4 3 2]
 [2 5 6 7]
 [6 7 8 4]]


In [3]:
arr_zeros = np.zeros((5,5))
arr_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
arr_eye = np.eye(4)
arr_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
var = np.random.random((4,9))
var

array([[0.67234131, 0.22070838, 0.32808992, 0.46439095, 0.16104062,
        0.63773021, 0.34955244, 0.71944092, 0.07183464],
       [0.32197194, 0.37238846, 0.80309757, 0.12110397, 0.09221048,
        0.47746911, 0.79919847, 0.77111699, 0.33948068],
       [0.24160192, 0.81724942, 0.46942381, 0.8109683 , 0.14624248,
        0.20733233, 0.03857427, 0.5613223 , 0.15563527],
       [0.45976232, 0.06061257, 0.39397187, 0.89797591, 0.18328586,
        0.66076975, 0.54118397, 0.84911886, 0.59072191]])

In [6]:
m = np.ones((2,5))
m

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
a = np.linspace(0,1,10)
a

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [8]:
print(var.shape)

(4, 9)


In [9]:
print(var.size)

36


In [10]:
var.reshape(3,12)
var

array([[0.67234131, 0.22070838, 0.32808992, 0.46439095, 0.16104062,
        0.63773021, 0.34955244, 0.71944092, 0.07183464],
       [0.32197194, 0.37238846, 0.80309757, 0.12110397, 0.09221048,
        0.47746911, 0.79919847, 0.77111699, 0.33948068],
       [0.24160192, 0.81724942, 0.46942381, 0.8109683 , 0.14624248,
        0.20733233, 0.03857427, 0.5613223 , 0.15563527],
       [0.45976232, 0.06061257, 0.39397187, 0.89797591, 0.18328586,
        0.66076975, 0.54118397, 0.84911886, 0.59072191]])

In [11]:
A = np.array([[1,5,3],[7,6,5]])
B = np.array([[6,3,0],[1,4,9]])
print(A, '\n\n', B)

[[1 5 3]
 [7 6 5]] 

 [[6 3 0]
 [1 4 9]]


In [12]:
A + B

array([[ 7,  8,  3],
       [ 8, 10, 14]])

In [13]:
A * 10

array([[10, 50, 30],
       [70, 60, 50]])

In [14]:
A * B

array([[ 6, 15,  0],
       [ 7, 24, 45]])

In [15]:
A / B

/var/folders/f3/_st5g9tj5bs69f2k8ttz8mwh0000gn/T/ipykernel_37301/3006334257.py:1: RuntimeWarning: divide by zero encountered in divide
  A / B


array([[0.16666667, 1.66666667,        inf],
       [7.        , 1.5       , 0.55555556]])

In [16]:
np.matmul(A, B.T)

array([[21, 48],
       [60, 76]])

In [17]:
np.log(A)

array([[0.        , 1.60943791, 1.09861229],
       [1.94591015, 1.79175947, 1.60943791]])

In [18]:
A[0] @ B[0]

21

In [19]:
print(A, '\n\n', B)
A > B

[[1 5 3]
 [7 6 5]] 

 [[6 3 0]
 [1 4 9]]


array([[False,  True,  True],
       [ True,  True, False]])

In [20]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
print(arr1, '\n\n', arr2)
print(np.array_equal(arr1, arr2))

print(A, '\n\n', B)
print(np.array_equal(A, B))



[1 2 3] 

 [1 2 3]
True
[[1 5 3]
 [7 6 5]] 

 [[6 3 0]
 [1 4 9]]
False


In [21]:
print(np.array_equal(A,A))

True


In [22]:
print(A,'\n')
print(np.sum(A, axis=1))

[[1 5 3]
 [7 6 5]] 

[ 9 18]


In [23]:
print(B, '\n')
print(np.sum(B, axis=0))

[[6 3 0]
 [1 4 9]] 

[7 7 9]


In [24]:
print(A, '\n')
print(np.sum(A))

[[1 5 3]
 [7 6 5]] 

27


In [25]:
print(A, '\n')
print(np.max(A))

[[1 5 3]
 [7 6 5]] 

7


In [26]:
print(A, '\n')
print(np.max(A, axis=1))

[[1 5 3]
 [7 6 5]] 

[5 7]


In [27]:
print(B, '\n')
print(np.mean(B, axis=0))

[[6 3 0]
 [1 4 9]] 

[3.5 3.5 4.5]


In [28]:
print(A, '\n', B, '\n')
print(np.concatenate([A,B], axis=1))

[[1 5 3]
 [7 6 5]] 
 [[6 3 0]
 [1 4 9]] 

[[1 5 3 6 3 0]
 [7 6 5 1 4 9]]


In [29]:
print(A, '\n', B, '\n')
print(np.concatenate([B,A], axis=0))

[[1 5 3]
 [7 6 5]] 
 [[6 3 0]
 [1 4 9]] 

[[6 3 0]
 [1 4 9]
 [1 5 3]
 [7 6 5]]


In [30]:
C = np.array(np.arange(33,1,-2))
C = C.reshape(4,4)
C

array([[33, 31, 29, 27],
       [25, 23, 21, 19],
       [17, 15, 13, 11],
       [ 9,  7,  5,  3]])

In [31]:
C_copy = np.copy(C)
C_copy

array([[33, 31, 29, 27],
       [25, 23, 21, 19],
       [17, 15, 13, 11],
       [ 9,  7,  5,  3]])

In [32]:
print(np.sort(C_copy, axis=1))

[[27 29 31 33]
 [19 21 23 25]
 [11 13 15 17]
 [ 3  5  7  9]]


In [33]:
print(C_copy, '\n')
print(C_copy[:,1])

[[33 31 29 27]
 [25 23 21 19]
 [17 15 13 11]
 [ 9  7  5  3]] 

[31 23 15  7]


In [34]:
print(C_copy, '\n')
print(C_copy[2,:])

[[33 31 29 27]
 [25 23 21 19]
 [17 15 13 11]
 [ 9  7  5  3]] 

[17 15 13 11]


In [35]:
print(C_copy, '\n')
print(C_copy[1:3,1:3])

[[33 31 29 27]
 [25 23 21 19]
 [17 15 13 11]
 [ 9  7  5  3]] 

[[23 21]
 [15 13]]


In [36]:
print(C_copy, '\n')
print(C_copy[1:3])

[[33 31 29 27]
 [25 23 21 19]
 [17 15 13 11]
 [ 9  7  5  3]] 

[[25 23 21 19]
 [17 15 13 11]]


In [37]:
print(C_copy, '\n')
print(C_copy[np.arange(4), np.arange(4)])

[[33 31 29 27]
 [25 23 21 19]
 [17 15 13 11]
 [ 9  7  5  3]] 

[33 23 13  3]


In [38]:
print(C_copy, '\n')
idx = np.arange(C_copy.shape[0])
main_diagonal = C_copy[idx, idx]
secondary_diagonal = C_copy[idx, C_copy.shape[1] - 1 - idx]
print(f"main diagonal: {main_diagonal}")
print(f"secondary diagonal: {main_diagonal}")

[[33 31 29 27]
 [25 23 21 19]
 [17 15 13 11]
 [ 9  7  5  3]] 

main diagonal: [33 23 13  3]
secondary diagonal: [33 23 13  3]


In [39]:
print(C_copy, '\n')
print(C_copy[((C_copy >= 5) & (C_copy <= 15))])

[[33 31 29 27]
 [25 23 21 19]
 [17 15 13 11]
 [ 9  7  5  3]] 

[15 13 11  9  7  5]


In [40]:
print(C_copy, '\n')
print(C_copy[(C_copy % 3 == 0)])

[[33 31 29 27]
 [25 23 21 19]
 [17 15 13 11]
 [ 9  7  5  3]] 

[33 27 21 15  9  3]


In [41]:
print(C_copy, '\n')
print(C_copy.ravel())

[[33 31 29 27]
 [25 23 21 19]
 [17 15 13 11]
 [ 9  7  5  3]] 

[33 31 29 27 25 23 21 19 17 15 13 11  9  7  5  3]


In [42]:
def zeros_and_ones_matrix(size):
    matrix = np.zeros((size,size))
    matrix[0, :] = 1
    matrix[-1, :] = 1
    matrix[:,0] = 1
    matrix[:,-1] = 1
    return matrix

print(zeros_and_ones_matrix(9))

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [43]:
def celsius_to_fahrenheit(temperatures_list):
    return temperatures_list * (9/5) + 32
temperatures = np.array([-5, 0 , 18, 23, 31, 40])

print(f"Celsius: {temperatures}")
print(f"Fahrenheit: {celsius_to_fahrenheit(temperatures)}")

Celsius: [-5  0 18 23 31 40]
Fahrenheit: [ 23.   32.   64.4  73.4  87.8 104. ]


In [45]:
T = np.array([1,2,3])
Y = np.array([3,4,5])

print(f"{T}\n{Y}\n")
mask = np.isin(T,Y)
print(np.isin(T,Y))
print(T[mask])

[1 2 3]
[3 4 5]

[False False  True]
[3]


In [47]:
print(f"{T}\n{Y}\n")
Z = np.concatenate((T,Y))
print(f"{Z}\n")
print(np.unique(Z))

[1 2 3]
[3 4 5]

[1 2 3 3 4 5]

[1 2 3 4 5]


In [49]:
print(f"{T}\n")
print(f"{T.astype(float)}")

[1 2 3]

[1. 2. 3.]


In [54]:
G = np.array([x for x in range(123,1989,15)])
print(f"{G}\n")
print(f"{G[(G % 7 == 0)]}")

[ 123  138  153  168  183  198  213  228  243  258  273  288  303  318
  333  348  363  378  393  408  423  438  453  468  483  498  513  528
  543  558  573  588  603  618  633  648  663  678  693  708  723  738
  753  768  783  798  813  828  843  858  873  888  903  918  933  948
  963  978  993 1008 1023 1038 1053 1068 1083 1098 1113 1128 1143 1158
 1173 1188 1203 1218 1233 1248 1263 1278 1293 1308 1323 1338 1353 1368
 1383 1398 1413 1428 1443 1458 1473 1488 1503 1518 1533 1548 1563 1578
 1593 1608 1623 1638 1653 1668 1683 1698 1713 1728 1743 1758 1773 1788
 1803 1818 1833 1848 1863 1878 1893 1908 1923 1938 1953 1968 1983]

[ 168  273  378  483  588  693  798  903 1008 1113 1218 1323 1428 1533
 1638 1743 1848 1953]


In [55]:
A = np.arange(3,3*50 + 1, 3)
B = np.arange(5,5*50 + 1, 3)
print(f"{A}\n{B}\n")
print(f"{A.sum() + B.sum()}")

[  3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51  54
  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105 108
 111 114 117 120 123 126 129 132 135 138 141 144 147 150]
[  5   8  11  14  17  20  23  26  29  32  35  38  41  44  47  50  53  56
  59  62  65  68  71  74  77  80  83  86  89  92  95  98 101 104 107 110
 113 116 119 122 125 128 131 134 137 140 143 146 149 152 155 158 161 164
 167 170 173 176 179 182 185 188 191 194 197 200 203 206 209 212 215 218
 221 224 227 230 233 236 239 242 245 248]

14198


In [56]:
def replace_negatives(array):
    result = array.copy()
    result[result < 0] = result[result < 0] ** 2
    return result

F = np.array([4,-3,-5,1,8,9,-7,-2,0])
print(f"{F}\n")
print(replace_negatives(F))

[ 4 -3 -5  1  8  9 -7 -2  0]

[ 4  9 25  1  8  9 49  4  0]


In [60]:
G = np.random.randint(-5,5,1000)
print(G)

values, counts = np.unique(G, return_counts=True)
result = list(zip(values, counts))
print(f"\n{result}")

[-2  4 -2 -1 -3 -1  2 -2  0  2 -4 -4 -5 -4 -5 -3 -4  4 -4  4  3 -4  3  3
  2  4 -2  1  1 -2  2 -5  4  2 -2  1 -4 -4  1 -2 -1  4 -3 -2  0 -4  0 -4
  3 -3 -4  2  3  0  2  4  0  3  1  3  2 -4 -5  4  3  1 -5  0 -3 -2  0  1
 -3  3 -4 -2 -3 -5 -4 -2 -2  2 -1 -2  1 -1  4 -3  3 -4 -1  2  0 -1  0 -3
  2  4  4  1  0  4  0  2  0 -1 -4 -3  4  3 -4  1 -1 -3 -2  2  3 -3  4  3
  3  2  1  3  4 -4 -1  4 -1  2 -2  0  0  1  2 -4 -5  0  4 -1  1 -5 -2  4
 -1  2  0  1  3 -1  4  3  0  0 -5  3  2 -2  1  4 -4 -5 -3  1  3 -4  4 -5
  3 -1  4 -5  0 -5 -4  0 -3  4  2 -4  3 -2  2  1 -2  4 -1  3  1  0  0 -5
  2 -1 -2 -1 -3  4  1  4 -2 -4  4  0  3 -1 -1  4  4  3 -3  3 -2  4  4  4
  2  1 -2  1  0 -5 -3  2  1 -5  3 -3 -5  3  1 -3 -5  4  3  2  3 -2 -3  3
 -4  4  3  0 -3 -4 -2 -2 -5  4 -2 -2  3  4 -1  4 -2 -4 -1 -2  0  0  4  0
  3 -3 -2 -2  2  2  0  1  0 -1  0  2  0 -3  0  4  0  3  0  2 -4  3 -3  0
  0 -5 -2 -1  3  3  3  1  2 -2  3 -5  4  0  4 -3  1 -2 -2  0 -3  3 -1  3
 -5  1 -1 -2  4 -5 -2 -4 -2  2  2 -3  1  0 -5  2 -1

In [64]:
n = 4
M = np.random.randint(-20, 20, (n,n))
print(f"{M}\n")
print(f"{np.flipud(M.T)}\n")

[[  3 -17  11 -12]
 [ 13  -9   8  11]
 [  5  19  17 -10]
 [ 15   2  10   4]]

[[-12  11 -10   4]
 [ 11   8  17  10]
 [-17  -9  19   2]
 [  3  13   5  15]]



In [65]:
def chess_board_matrix(n):
    board = np.zeros((n,n))
    board[::2, 1::2] = 1
    board[1::2] = 1
    return board

print(chess_board_matrix(8))

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [68]:
rand = np.random.RandomState(7875)
P = rand.randint(-50,50,(4,4))
Q = rand.randint(-50,50,(4,4))
print(f"{P}\n\n{Q}")

[[-11  -9 -19  41]
 [ 10 -48 -17  13]
 [-37  25  26 -28]
 [ -3 -15  -9  10]]

[[-14 -35  36 -21]
 [ 26 -46  31 -42]
 [  4 -18  14 -22]
 [ 15 -40 -24  41]]


In [78]:
rows = [0, Q.shape[0]-1]
cols = [0, Q.shape[1]-1]

print(Q[rows, cols])

[-14  41]
