In [2]:
import numpy as np

In [3]:
arr = np.array([1,4,5,9,3,5])
arr

array([1, 4, 5, 9, 3, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.dtype('b') # byte
np.dtype('i4') # == np.int32 'i' signed integer
np.dtype('u1') # == np.uint8 'u' unsigned integer
np.dtype('f8') # == np.int64 'f' floating point
np.dtype('c16') # == np.complex128 'c' complez floating point
np.dtype('S5') # 'S' 'a' string
np.dtype('U') # == np.str_ 'U' Unicode string
np.dtype('V') # == np.void 'V' raw data (void)

dtype('V')

In [9]:
arr = np.array([[3,4,5], [6,8,9]])
arr

array([[3, 4, 5],
       [6, 8, 9]])

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [11]:
np.zeros_like(arr)

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
np.zeros(arr.shape)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.empty((8,8))

array([[4.67296746e-307, 1.69121096e-306, 9.34604358e-307,
        1.89146896e-307, 7.56571288e-307, 3.11525958e-307,
        1.24610723e-306, 1.29061142e-306],
       [5.53353523e-322, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.0000000

In [15]:
np.full((2,2), True)

array([[ True,  True],
       [ True,  True]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
print(arr.shape, arr.ndim, arr.size, arr.dtype)

(2, 3) 2 6 int64


In [19]:
arr

array([[3, 4, 5],
       [6, 8, 9]])

In [20]:
arr[0]

array([3, 4, 5])

In [21]:
arr[0,1]

np.int64(4)

In [22]:
arr[0,1:]

array([4, 5])

In [23]:
arr[0,:]

array([3, 4, 5])

In [24]:
arr[0,:2]

array([3, 4])

In [25]:
a = np.random.random((5,5))*20
a

array([[14.7071418 ,  0.70041422,  0.70014422, 16.75199869,  6.64749191],
       [10.75975158,  8.73688299, 12.43388199,  8.85949917,  4.14053932],
       [18.27548743, 12.82859343, 14.24915372, 19.27852968, 16.54188554],
       [ 4.56457116, 10.25836962,  1.63560783, 16.63076976, 19.213484  ],
       [ 7.27956626,  5.18341877,  2.96606627, 12.27210594, 10.22384054]])

In [26]:
a[1:3,2:4]

array([[12.43388199,  8.85949917],
       [14.24915372, 19.27852968]])

In [27]:
a[::2]

array([[14.7071418 ,  0.70041422,  0.70014422, 16.75199869,  6.64749191],
       [18.27548743, 12.82859343, 14.24915372, 19.27852968, 16.54188554],
       [ 7.27956626,  5.18341877,  2.96606627, 12.27210594, 10.22384054]])

In [28]:
a[::2,::3]

array([[14.7071418 , 16.75199869],
       [18.27548743, 19.27852968],
       [ 7.27956626, 12.27210594]])

In [30]:
lst = [1,3,5,7,9,11]
arr = np.array(lst)
print(lst, arr)
reb_l = lst[:]
reb_ar = arr[:]
print(arr.base, reb_ar.base)

[1, 3, 5, 7, 9, 11] [ 1  3  5  7  9 11]
None [ 1  3  5  7  9 11]


In [31]:
arr_c = arr.copy()
print(arr, arr_c)
print(arr.base, arr_c.base)

[ 1  3  5  7  9 11] [ 1  3  5  7  9 11]
None None


In [32]:
arr2 = np.arange(1,5,0.5)
arr2

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [34]:
np.linspace(12.4, 23.7, 5)

array([12.4  , 15.225, 18.05 , 20.875, 23.7  ])

In [35]:
arr2.size

8

In [36]:
arr2.reshape((2,4))

array([[1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5]])

In [3]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
arr = arr[np.newaxis,:]
arr

array([[1, 2, 3]])

In [5]:
arr.ndim

2

In [6]:
a = np.zeros((2,2))
b = np.ones((2,2))
print(a, "\n\n", b)

[[0. 0.]
 [0. 0.]] 

 [[1. 1.]
 [1. 1.]]


In [7]:
np.concatenate([a,b], axis=0)

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.concatenate([a,b], axis=1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [9]:
a = np.zeros((2,2))
b = np.ones((2,3))
print(a, "\n\n", b)

[[0. 0.]
 [0. 0.]] 

 [[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
np.concatenate([a,b], axis=1)

array([[0., 0., 1., 1., 1.],
       [0., 0., 1., 1., 1.]])

In [13]:
np.hstack([a,b])

array([[0., 0., 1., 1., 1.],
       [0., 0., 1., 1., 1.]])

In [15]:
np.vstack([a, np.full((2,2),12)])

array([[ 0.,  0.],
       [ 0.,  0.],
       [12., 12.],
       [12., 12.]])

In [19]:
b = np.random.randint(1,10,10)
b

array([6, 9, 7, 4, 2, 1, 1, 6, 1, 4], dtype=int32)

In [22]:
m1, m2, m3 = np.split(b, [2, 7])
print(m1, m2, m3)

[6 9] [7 4 2 1 1] [6 1 4]


In [24]:
b = np.random.randint(1,10,(3,4))
b

array([[8, 1, 4, 1],
       [7, 5, 8, 6],
       [9, 9, 4, 9]], dtype=int32)

In [25]:
m1, m2 = np.hsplit(b, [2])
print(m1, '\n\n', m2)

[[8 1]
 [7 5]
 [9 9]] 

 [[4 1]
 [8 6]
 [4 9]]


In [26]:
b = np.random.randint(1,10,10)
b

array([8, 5, 1, 5, 1, 3, 7, 6, 7, 3], dtype=int32)

In [27]:
print(b < 4)

[False False  True False  True  True False False False  True]


In [28]:
print((b>2) & (b<5))

[False False False False False  True False False False  True]


### Fancy Indexing

In [29]:
print(b, b[[1,3]])

[8 5 1 5 1 3 7 6 7 3] [5 5]


In [30]:
c = np.random.randint(0,11,(4,4))
c

array([[ 3,  9,  8,  0],
       [ 2,  6,  3, 10],
       [ 7,  1,  6,  3],
       [ 8,  5,  1,  4]], dtype=int32)

In [31]:
c[[1,3],[0,2]]

array([2, 1], dtype=int32)

In [32]:
b

array([8, 5, 1, 5, 1, 3, 7, 6, 7, 3], dtype=int32)

In [34]:
mask = b < 3
mask

array([False, False,  True, False,  True, False, False, False, False,
       False])

In [35]:
b[mask]

array([1, 1], dtype=int32)

In [36]:
c<5

array([[ True, False, False,  True],
       [ True, False,  True, False],
       [False,  True, False,  True],
       [False, False,  True,  True]])

In [37]:
c[c<5]

array([3, 0, 2, 3, 1, 3, 1, 4], dtype=int32)

In [40]:
y = np.random.randint(0,10,(3,3))
z = np.random.randint(0,10,(3,3))

print(y, '\n\n', z)
print(y+z)

[[6 6 9]
 [2 4 1]
 [4 6 3]] 

 [[6 2 3]
 [5 0 8]
 [9 8 2]]
[[12  8 12]
 [ 7  4  9]
 [13 14  5]]


In [41]:
y@z

array([[147,  84,  84],
       [ 41,  12,  40],
       [ 81,  32,  66]], dtype=int32)

In [42]:
np.matmul(y,z)

array([[147,  84,  84],
       [ 41,  12,  40],
       [ 81,  32,  66]], dtype=int32)

In [43]:
y*5

array([[30, 30, 45],
       [10, 20,  5],
       [20, 30, 15]], dtype=int32)

In [44]:
X = np.random.randint(1,20,5)
X

array([ 6,  3,  7,  7, 16], dtype=int32)

In [46]:
Y = np.zeros_like(X)
for i in range(0,5):
    Y[i] = X[i]*5
Y

array([30, 15, 35, 35, 80], dtype=int32)

In [48]:
def inv(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1,10,5)
print(values, inv(values))

big = np.random.randint(1,100,1000000)

%timeit inv(big)
%timeit (1.0/big)

[7 6 2 4 6] [0.14285714 0.16666667 0.5        0.25       0.16666667]
6.07 s ± 162 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
7.93 ms ± 348 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Agregadores

In [49]:
y

array([[6, 6, 9],
       [2, 4, 1],
       [4, 6, 3]], dtype=int32)

In [50]:
np.add.reduce(y)

array([12, 16, 13])

In [51]:
np.add.reduce(y, axis=1)

array([21,  7, 13])

In [52]:
np.multiply.reduce(y)

array([ 48, 144,  27])

In [53]:
np.sum(y)

np.int64(41)

In [54]:
np.mean(y)

np.float64(4.555555555555555)

In [55]:
np.std(y)

np.float64(2.3147407395555177)

In [56]:
np.max(y)

np.int32(9)

In [59]:
print(y)
np.add.accumulate(y)

[[6 6 9]
 [2 4 1]
 [4 6 3]]


array([[ 6,  6,  9],
       [ 8, 10, 10],
       [12, 16, 13]])

In [60]:
np.multiply.accumulate(y)

array([[  6,   6,   9],
       [ 12,  24,   9],
       [ 48, 144,  27]])

In [61]:
np.median(y)

np.float64(4.0)

In [63]:
k = np.array([[1.2,5.6],[np.nan,-4.5]])
l = np.array([[1.2,5.6],[5,-4.5]])
print(k, "\n\n", l)
k+l

[[ 1.2  5.6]
 [ nan -4.5]] 

 [[ 1.2  5.6]
 [ 5.  -4.5]]


array([[ 2.4, 11.2],
       [ nan, -9. ]])

In [64]:
np.nansum(k)

np.float64(2.3)

In [3]:
arr = np.arange(3)
print(arr)
print(arr + 5)

[0 1 2]
[5 6 7]


In [4]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [5]:
np.ones((3,1)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [6]:
A = np.arange(4)
A

array([0, 1, 2, 3])

In [7]:
A + 7

array([ 7,  8,  9, 10])

In [9]:
B = np.random.randint(1,19,(4,4))
B

array([[ 2,  4, 16, 12],
       [ 3, 15, 12,  6],
       [13,  5,  3, 17],
       [10,  5, 13,  1]], dtype=int32)

In [10]:
B + A

array([[ 2,  5, 18, 15],
       [ 3, 16, 14,  9],
       [13,  6,  5, 20],
       [10,  6, 15,  4]])

In [11]:
C = np.arange(5,9).T
print(C)

[5 6 7 8]


In [12]:
C < 3

array([False, False, False, False])

In [13]:
B

array([[ 2,  4, 16, 12],
       [ 3, 15, 12,  6],
       [13,  5,  3, 17],
       [10,  5, 13,  1]], dtype=int32)

In [14]:
np.sort(B)

array([[ 2,  4, 12, 16],
       [ 3,  6, 12, 15],
       [ 3,  5, 13, 17],
       [ 1,  5, 10, 13]], dtype=int32)

In [15]:
np.sort(B, axis=0)

array([[ 2,  4,  3,  1],
       [ 3,  5, 12,  6],
       [10,  5, 13, 12],
       [13, 15, 16, 17]], dtype=int32)

In [16]:
B

array([[ 2,  4, 16, 12],
       [ 3, 15, 12,  6],
       [13,  5,  3, 17],
       [10,  5, 13,  1]], dtype=int32)

In [17]:
print(B)
B.sort()
print('\n',B)

[[ 2  4 16 12]
 [ 3 15 12  6]
 [13  5  3 17]
 [10  5 13  1]]

 [[ 2  4 12 16]
 [ 3  6 12 15]
 [ 3  5 13 17]
 [ 1  5 10 13]]
