In [2]:
import numpy as np

In [5]:
arr_1 = np.array([3,5,6,2,2])
print(arr_1)
arr_2 = np.array([[5,4,3,2],[2,5,6,7]])
print('\n', arr_2)
arr_3 = np.array([[5,4,3,2],[2,5,6,7],[6,7,8,4]])
print('\n', arr_3)

[3 5 6 2 2]

 [[5 4 3 2]
 [2 5 6 7]]

 [[5 4 3 2]
 [2 5 6 7]
 [6 7 8 4]]


In [6]:
arr_zeros = np.zeros((5,5))
arr_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
arr_eye = np.eye(4)
arr_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
var = np.random.random((4,9))
var

array([[0.52044172, 0.82079509, 0.32774478, 0.56934007, 0.34366251,
        0.69094682, 0.40652706, 0.91476116, 0.99198835],
       [0.69953831, 0.47891716, 0.07878079, 0.48942824, 0.62467455,
        0.30032217, 0.13282055, 0.09986256, 0.73034236],
       [0.10983291, 0.43252355, 0.43262323, 0.49767304, 0.59874984,
        0.16164111, 0.51181226, 0.76421218, 0.07243142],
       [0.23558971, 0.39522305, 0.84966848, 0.70738321, 0.67276999,
        0.61553037, 0.73751134, 0.59193876, 0.58322758]])

In [12]:
m = np.ones((2,5))
m

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
a = np.linspace(0,1,10)
a

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
print(var.shape)

(4, 9)


In [17]:
print(var.size)

36


In [18]:
var.reshape(3,12)
var

array([[0.52044172, 0.82079509, 0.32774478, 0.56934007, 0.34366251,
        0.69094682, 0.40652706, 0.91476116, 0.99198835],
       [0.69953831, 0.47891716, 0.07878079, 0.48942824, 0.62467455,
        0.30032217, 0.13282055, 0.09986256, 0.73034236],
       [0.10983291, 0.43252355, 0.43262323, 0.49767304, 0.59874984,
        0.16164111, 0.51181226, 0.76421218, 0.07243142],
       [0.23558971, 0.39522305, 0.84966848, 0.70738321, 0.67276999,
        0.61553037, 0.73751134, 0.59193876, 0.58322758]])

In [23]:
A = np.array([[1,5,3],[7,6,5]])
B = np.array([[6,3,0],[1,4,9]])
print(A, '\n\n', B)

[[1 5 3]
 [7 6 5]] 

 [[6 3 0]
 [1 4 9]]


In [24]:
A + B

array([[ 7,  8,  3],
       [ 8, 10, 14]])

In [25]:
A * 10

array([[10, 50, 30],
       [70, 60, 50]])

In [26]:
A * B

array([[ 6, 15,  0],
       [ 7, 24, 45]])

In [27]:
A / B

C:\Users\aleja\AppData\Local\Temp\ipykernel_25412\3006334257.py:1: RuntimeWarning: divide by zero encountered in divide
  A / B


array([[0.16666667, 1.66666667,        inf],
       [7.        , 1.5       , 0.55555556]])

In [28]:
np.matmul(A, B.T)

array([[21, 48],
       [60, 76]])

In [29]:
np.log(A)

array([[0.        , 1.60943791, 1.09861229],
       [1.94591015, 1.79175947, 1.60943791]])

In [30]:
A[0] @ B[0]

np.int64(21)

In [31]:
print(A, '\n\n', B)
A > B

[[1 5 3]
 [7 6 5]] 

 [[6 3 0]
 [1 4 9]]


array([[False,  True,  True],
       [ True,  True, False]])

In [33]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
print(arr1, '\n\n', arr2)
print(np.array_equal(arr1, arr2))

print(A, '\n\n', B)
print(np.array_equal(A, B))



[1 2 3] 

 [1 2 3]
True
[[1 5 3]
 [7 6 5]] 

 [[6 3 0]
 [1 4 9]]
False


In [34]:
print(np.array_equal(A,A))

True


In [38]:
print(A,'\n')
print(np.sum(A, axis=1))

[[1 5 3]
 [7 6 5]] 

[ 9 18]


In [39]:
print(B, '\n')
print(np.sum(B, axis=0))

[[6 3 0]
 [1 4 9]] 

[7 7 9]


In [41]:
print(A, '\n')
print(np.sum(A))

[[1 5 3]
 [7 6 5]] 

27


In [42]:
print(A, '\n')
print(np.max(A))

[[1 5 3]
 [7 6 5]] 

7


In [43]:
print(A, '\n')
print(np.max(A, axis=1))

[[1 5 3]
 [7 6 5]] 

[5 7]


In [44]:
print(B, '\n')
print(np.mean(B, axis=0))

[[6 3 0]
 [1 4 9]] 

[3.5 3.5 4.5]


In [48]:
print(A, '\n', B, '\n')
print(np.concatenate([A,B], axis=1))

[[1 5 3]
 [7 6 5]] 
 [[6 3 0]
 [1 4 9]] 

[[1 5 3 6 3 0]
 [7 6 5 1 4 9]]


In [49]:
print(A, '\n', B, '\n')
print(np.concatenate([B,A], axis=0))

[[1 5 3]
 [7 6 5]] 
 [[6 3 0]
 [1 4 9]] 

[[6 3 0]
 [1 4 9]
 [1 5 3]
 [7 6 5]]


In [51]:
C = np.array(np.arange(33,1,-2))
C = C.reshape(4,4)
C

array([[33, 31, 29, 27],
       [25, 23, 21, 19],
       [17, 15, 13, 11],
       [ 9,  7,  5,  3]])

In [53]:
C_copy = np.copy(C)
C_copy

array([[33, 31, 29, 27],
       [25, 23, 21, 19],
       [17, 15, 13, 11],
       [ 9,  7,  5,  3]])

In [54]:
print(np.sort(C_copy, axis=1))

[[27 29 31 33]
 [19 21 23 25]
 [11 13 15 17]
 [ 3  5  7  9]]


In [56]:
print(C_copy, '\n')
print(C_copy[:,1])

[[33 31 29 27]
 [25 23 21 19]
 [17 15 13 11]
 [ 9  7  5  3]] 

[31 23 15  7]


In [57]:
print(C_copy, '\n')
print(C_copy[2,:])

[[33 31 29 27]
 [25 23 21 19]
 [17 15 13 11]
 [ 9  7  5  3]] 

[17 15 13 11]


In [58]:
print(C_copy, '\n')
print(C_copy[1:3,1:3])

[[33 31 29 27]
 [25 23 21 19]
 [17 15 13 11]
 [ 9  7  5  3]] 

[[23 21]
 [15 13]]


In [60]:
print(C_copy, '\n')
print(C_copy[1:3])

[[33 31 29 27]
 [25 23 21 19]
 [17 15 13 11]
 [ 9  7  5  3]] 

[[25 23 21 19]
 [17 15 13 11]]


In [61]:
print(C_copy, '\n')
print(C_copy[np.arange(4), np.arange(4)])

[[33 31 29 27]
 [25 23 21 19]
 [17 15 13 11]
 [ 9  7  5  3]] 

[33 23 13  3]
