In [1]:
5+2
5/8
5-3

[1] 7

[1] 0.625

[1] 2

In [2]:
x = 5 # Comment
print(x)

[1] 5


μ

In [3]:
x <- 5 # asignación
print(x)

[1] 5


In [4]:
edades <- c(15,20,30)
edades
edades[1:2]
edades[-1]
x2 <- edades[-1]
x2

[1] 15 20 30

[1] 15 20

[1] 20 30

[1] 20 30

In [5]:
edades<25

[1]  TRUE  TRUE FALSE

In [6]:
estatura <- c(170, 158, 169)
estatura

[1] 170 158 169

In [7]:
cbind(edades, estatura)
rbind(edades, estatura)

edades estatura
[1,] 15     170     
[2,] 20     158     
[3,] 30     169

[,1] [,2] [,3]
edades    15   20   30 
estatura 170  158  169

In [8]:
marco1 <- data.frame(Edades = edades, Estatura = estatura)
marco1

Edades Estatura
1 15     170     
2 20     158     
3 30     169

In [9]:
marco1["Edades"]

Edades
1 15    
2 20    
3 30

In [10]:
marco1$Estatura

[1] 170 158 169

In [11]:
dim(marco1)

[1] 3 2

In [12]:
dim(marco1["Edades"])

[1] 3 1

In [13]:
length(marco1$Edades)

[1] 3

In [14]:
marco1[1,1]

[1] 15

In [15]:
marco1[1,]

Edades Estatura
1 15     170

In [16]:
marco1[,1]

[1] 15 20 30

In [17]:
marco1[2:3,1]

[1] 20 30

In [18]:
marco1[2:3,-1]

[1] 158 169

In [21]:
install.packages("readxl")
library(readxl)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [22]:
matriz1 <- matrix(c(15,170,20,158,30,169), ncol = 2, byrow = TRUE)
matriz1

[,1] [,2]
[1,] 15   170 
[2,] 20   158 
[3,] 30   169

In [23]:
matriz2 <- matrix(c("Juan", "Pedro", "Luis", "Pablo"), ncol = 2, byrow = TRUE)
matriz2

[,1] [,2] 
[1,] Juan Pedro
[2,] Luis Pablo

In [24]:
marco2 <- data.frame(Nombres = c("Juan", "Pedro", "Luis", "Pablo"), Edades = c(15,23,18,30))
marco2
marco2["Nombres"]

Nombres Edades
1 Juan    15    
2 Pedro   23    
3 Luis    18    
4 Pablo   30

Nombres
1 Juan   
2 Pedro  
3 Luis   
4 Pablo

In [25]:
sum(marco2["Edades"])

[1] 86

In [26]:
summary(marco2)

   Nombres              Edades     
 Length:4           Min.   :15.00  
 Class :character   1st Qu.:17.25  
 Mode  :character   Median :20.50  
                    Mean   :21.50  
                    3rd Qu.:24.75  
                    Max.   :30.00  

In [27]:
matriz3 <- matrix(c(15,170,20,158,30,169,25), ncol = 2, byrow = TRUE)
matriz3

Warning message in matrix(c(15, 170, 20, 158, 30, 169, 25), ncol = 2, byrow = TRUE):
“data length [7] is not a sub-multiple or multiple of the number of rows [4]”


[,1] [,2]
[1,] 15   170 
[2,] 20   158 
[3,] 30   169 
[4,] 25    15

In [28]:
matriz4 <- matrix(c(15,170,20,158,30,169,25,"Hector"), ncol = 2, byrow = TRUE)
matriz4
matriz4[,1]

[,1] [,2]  
[1,] 15   170   
[2,] 20   158   
[3,] 30   169   
[4,] 25   Hector

[1] "15" "20" "30" "25"

In [29]:
sum(as.numeric(matriz4[,2]), na.rm = TRUE)
mean(as.numeric(matriz4[,2]), na.rm = TRUE)

Warning message:
“NAs introduced by coercion”


[1] 497

Warning message in mean(as.numeric(matriz4[, 2]), na.rm = TRUE):
“NAs introduced by coercion”


[1] 165.6667